# Generated by Django 3.2.2 on 2022-03-12 12:46

import crowdfunding.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('fund_cause', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('total_fund', models.IntegerField()),
                ('amount_raise', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='no-image', upload_to=crowdfunding.models.get_Funding_Image)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('ngo_certficate', models.ImageField(default='no-image', upload_to=crowdfunding.models.get_ngo_certificate)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundingUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('message_date', models.DateTimeField(auto_now=True)),
                ('funding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.funding')),
            ],
        ),
        migrations.CreateModel(
            name='FundingComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('message_date', models.DateTimeField(auto_now=True)),
                ('funding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.funding')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_donated', models.IntegerField()),
                ('donation_time', models.DateTimeField(auto_now=True)),
                ('donation_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('donar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('funding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.funding')),
            ],
        ),
    ]
