# Generated by Django 3.2.2 on 2022-03-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='ngo_certficate',
            new_name='ngo_certificate',
        ),
    ]
