# Generated by Django 3.2.2 on 2022-03-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_NGO',
            field=models.BooleanField(default=False),
        ),
    ]
