# Generated by Django 3.2.2 on 2022-03-12 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfunding', '0003_delete_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_donated', models.IntegerField()),
                ('donation_date', models.DateTimeField(auto_now=True)),
                ('donation_payment_id', models.CharField(max_length=100)),
                ('isPaid', models.BooleanField(default=False)),
                ('donation_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('donar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('funding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.funding')),
            ],
        ),
    ]
